<?php

/*
 * Generates the options page.  Fields generated by the
 * tool at the @link below.
 *
 * @link http://wpsettingsapi.jeroensormani.com/
 */


function pvcu_add_admin_menu() { 
	add_options_page(
		'Protect Version Controlled Updates',
		'PVCU Options',
		'manage_options',
		'pvcu-options',
		'pvcu_options_page' );
}

add_action( 'admin_menu', 'pvcu_add_admin_menu' );

function pvcu_settings_init() { 
	register_setting( 'pluginPage', 'pvcu_settings' );

	add_settings_section(
		'pvcu_plugin_action_settings',
		'Action Settings',
		'pvcu_plugin_action_callback', 
		'pluginPage'
	);

	add_settings_field( 
		'pvcu_plugins_action', 
		__( 'Plugins Action', 'pvcu' ), 
		'pvcu_plugins_action_render', 
		'pluginPage', 
		'pvcu_plugin_action_settings' 
	);

	add_settings_field( 
		'pvcu_themes_action', 
		__( 'Themes Action', 'pvcu' ), 
		'pvcu_themes_action_render', 
		'pluginPage', 
		'pvcu_plugin_action_settings' 
	);

	// Uncomment when able to stop core updates.

	// add_settings_field( 
	// 	'pvcu_core_action', 
	// 	__( 'Core Action', 'pvcu' ), 
	// 	'pvcu_core_action_render', 
	// 	'pluginPage', 
	// 	'pvcu_plugin_action_settings' 
	// );

	add_settings_section(
		'pvcu_plugin_modal_settings',
		'Modal Settings',
		'pvcu_plugin_modal_callback', 
		'pluginPage'
	);

	add_settings_field( 
		'pvcu_modal_title', 
		__( 'Title to display', 'pvcu' ), 
		'pvcu_modal_title_render', 
		'pluginPage', 
		'pvcu_plugin_modal_settings' 
	);

	add_settings_field( 
		'pvcu_modal_content', 
		__( 'Message to display', 'pvcu' ), 
		'pvcu_modal_content_render', 
		'pluginPage', 
		'pvcu_plugin_modal_settings' 
	);
}

add_action( 'admin_init', 'pvcu_settings_init' );

function pvcu_plugin_action_callback() { 
	echo __( '<p>For the two locations below, you can choose to have <em>no</em> protection, <em>warn</em> the user before a plugin update (with a modal window which the user must agree to before the update triggers), or <em>block</em> updates entirely.</p>', 'pvcu' );
}

function pvcu_plugins_action_render() { 
	$options = get_option( 'pvcu_settings' ); ?>
	<input type='radio' name='pvcu_settings[pvcu_plugins_action]' <?php checked( $options['pvcu_plugins_action'], 'none' ); ?> value='none'>None<br />
	<input type='radio' name='pvcu_settings[pvcu_plugins_action]' <?php checked( $options['pvcu_plugins_action'], 'warn' ); ?> value='warn'>Warn<br />
	<input type='radio' name='pvcu_settings[pvcu_plugins_action]' <?php checked( $options['pvcu_plugins_action'], 'block' ); ?> value='block'>Block
	<?php
}

function pvcu_themes_action_render() { 
	$options = get_option( 'pvcu_settings' ); ?>
	<input type='radio' name='pvcu_settings[pvcu_themes_action]' <?php checked( $options['pvcu_themes_action'], 'none' ); ?> value='none'>None<br />
	<input type='radio' name='pvcu_settings[pvcu_themes_action]' <?php checked( $options['pvcu_themes_action'], 'warn' ); ?> value='warn'>Warn<br />
	<input type='radio' name='pvcu_settings[pvcu_themes_action]' <?php checked( $options['pvcu_themes_action'], 'block' ); ?> value='block'>Block
	<?php
}

function pvcu_core_action_render() { 
	$options = get_option( 'pvcu_settings' ); ?>
	<input type='radio' name='pvcu_settings[pvcu_core_action]' <?php checked( $options['pvcu_core_action'], 'none' ); ?> value='none'>None<br />
	<input type='radio' name='pvcu_settings[pvcu_core_action]' <?php checked( $options['pvcu_core_action'], 'warn' ); ?> value='warn'>Warn<br />
	<input type='radio' name='pvcu_settings[pvcu_core_action]' <?php checked( $options['pvcu_core_action'], 'block' ); ?> value='block'>Block
	<?php
}

function pvcu_plugin_modal_callback() {
	echo __( '<p>You can set options below for the modal window the user will see for any sectio marked <em>warn</em> or <em>block</em> above.' );
}

function pvcu_modal_title_render() { 
	$options = get_option( 'pvcu_settings' ); ?>
 	<label>What title do you want to display on the modal window?</label><br />
 	<input type='text' name='pvcu_settings[pvcu_modal_title]' value='<?php echo $options[ 'pvcu_modal_title' ]; ?>'>
	<?php
}

function pvcu_modal_content_render() { 
	$options = get_option( 'pvcu_settings' ); ?>
 	<label>What message do you want to display on the modal window?</label><br />
	<textarea cols='40' rows='5' name='pvcu_settings[pvcu_modal_content]'><?php echo $options[ 'pvcu_modal_content' ]; ?></textarea>
	<?php
}

function pvcu_options_page() { ?>
	<form action='options.php' method='post'>
		<h1>Protect Version Controlled Updates</h1>
		<p>You can control the settings for the Protect Version Controlled Updates plugin below.</p>

		<?php
		settings_fields( 'pluginPage' );
		do_settings_sections( 'pluginPage' );
		submit_button();
		?>
	</form>
	<?php
}